export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const SIGN_UP = 'SIGN_UP';
export const LOG_IN = 'LOG_IN';
export const GET_USER_INFO = 'GET_USER_INFO';
export const SIGN_OUT = 'SIGN_OUT';
export const USER_INFO_VALIDATION = 'USER_INFO_VALIDATION'



export const GET_COORDINATORS = 'GET_COORDINATORS';
export const GET_ENTERPRISES = 'GET_ENTERPRISES'



